### ISSUE TITLE
Execution Issue

### ISSUE THREAD

**Issue by binaryhellstorm** [Nekmo/gkeep#16] opened 2019-09-02 19:19 UTC
When trying to run the script using any of the examples listed I get this error:

Traceback (most recent call last):
  File "gkeep", line 7, in <module>
    catch(cli)()
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\google_keep_tasks\exceptions.py", line 31, in wrap
    fn(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 1134, in invoke
    Command.invoke(self, ctx)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\google_keep_tasks\management.py", line 17, in cli
    keep.login(*get_auth(auth))
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\google_keep_tasks\auth.py", line 4, in get_auth
    return [val.rstrip('\n\r') for val in open(file).read().split(' ')]
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by taxilof** [comment] 2020-01-09 09:35
I had the same error with the recent development version. I specified the auth.txt file, this works for me:
`gkeep --auth ./auth.txt search-notes Test`
Although the file is in the current directory. Maybe the working directory of gkeep is not the current directory?

**Comment by Nekmo** [comment] 2020-02-16 16:39
Default directory is the current dir. I will try to reproduce this error. However, I can't try it on Windows.

**Comment by Nekmo** [comment] 2020-04-19 02:45
This is fixed in issue #19. Sorry for the delay.

**Closed by Nekmo** 2020-04-19 02:45 UTC
